quote/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path,include
from django.urls import re_path
from django.contrib.auth import views as auth_views

from .views import  QuoteCreateView, QuoteListView, QuoteEditView, QuoteDeleteView

urlpatterns = [
       
    path('cotizacion/add/', login_required(QuoteCreateView.as_view()), name='cotizacion_create'),
    path('cotizacion/list/', login_required(QuoteListView.as_view()), name='cotizacion_list'),
    path('cotizacion/edit/<int:pk>/',login_required(QuoteEditView.as_view()), name='cotizacion_editar'),
    path('cotizacion/eliminar/<int:pk>/',login_required(QuoteDeleteView.as_view()), name='cotizacion_eliminar'),

]

support_tech/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import handler404
from sales.views import page_not_found404

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('',include('sales.urls')),
    path('',include('quote.urls')),
    path('',include('inventory.urls')),
    path('',include('clients.urls')),
]

handler404 = page_not_found404

sales/models.py
from pickle import TRUE
from django.db import models
from datetime import datetime
from django.forms import model_to_dict

from inventory.models import  Producto
from clients.models import Cliente
from django.contrib.auth.models import User
# Create your models here.


class MetodoPagos(models.Model):
    metodoPago= models.CharField('Metodo de pago',max_length=45)
    def __str__(self):
        return self.metodoPago
    def toJSON(self):
        item = model_to_dict(self)

class Venta(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    vendedor = models.ForeignKey(User, on_delete=models.CASCADE)
    metodoPago = models.ForeignKey(MetodoPagos, on_delete=models.CASCADE)
    fecha_compra = models.DateField('Fecha de compra',default=datetime.now)
    subtotal = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    impuesto = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    descuento = models.DecimalField(default=0.00 , null=True, max_digits=9, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return self.cliente.nombre

    def toJSON(self):
        item = model_to_dict(self)
        item['cliente'] = self.cliente.toJSON()
        item['metodoPago'] = self.metodoPago.toJSON()
        item['subtotal'] = format(self.subtotal, '.2f')
        item['descuento'] = format(self.descuento, '.2f')
        item['total'] = format(self.total, '.2f')
        item['fecha_compra'] = self.fecha_compra.strftime('%Y-%m-%d')
        return item

    class Meta:
        verbose_name = 'Venta'
        verbose_name_plural = 'Ventas'
        ordering = ['id']


class DetVenta(models.Model):
    venta = models.ForeignKey(Venta, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    precio = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    cant = models.IntegerField(default=0)
    subtotal = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return self.producto.producto

    def toJSON(self):
        item = model_to_dict(self, exclude=['venta'])
        item['producto'] = self.producto.toJSON()
        item['precio'] = format(self.precio, '.2f')
        item['subtotal'] = format(self.subtotal, '.2f')
        return item

    class Meta:
        verbose_name = 'Detalle de Venta'
        verbose_name_plural = 'Detalle de Ventas'
        ordering = ['id']


class Cotizacion(models.Model):
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE)
    vendedor = models.ForeignKey(User, on_delete=models.CASCADE)
    fecha = models.DateField(default=datetime.now)
    subtotal = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    impuesto = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    descuento = models.DecimalField(default=0.00 , null=True, max_digits=9, decimal_places=2)
    total = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return self.cliente.nombre

    def toJSON(self):
        item = model_to_dict(self)
        item['cliente'] = self.cliente.toJSON()
        item['subtotal'] = format(self.subtotal, '.2f')
        item['descuento'] = format(self.descuento, '.2f')
        item['total'] = format(self.total, '.2f')
        item['fecha'] = self.fecha.strftime('%Y-%m-%d')
        return item

    class Meta:
        verbose_name = 'Cotizacion'
        verbose_name_plural = 'Cotizaciones'
        ordering = ['id']


class DetCotizacion(models.Model):
    cotizacion = models.ForeignKey(Cotizacion, on_delete=models.CASCADE)
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    precio = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)
    cant = models.IntegerField(default=0)
    subtotal = models.DecimalField(default=0.00, max_digits=9, decimal_places=2)

    def __str__(self):
        return self.producto.producto

    def toJSON(self):
        item = model_to_dict(self, exclude=['venta'])
        item['producto'] = self.producto.toJSON()
        item['precio'] = format(self.precio, '.2f')
        item['subtotal'] = format(self.subtotal, '.2f')
        return item

    class Meta:
        verbose_name = 'Detalle de cotizacion'
        verbose_name_plural = 'Detalle de cotizaciones'
        ordering = ['id']

support_tech/templates/base.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="{%  static 'img/support_tech1.jpg' %}">
  
    <title>
      {%  block title %}
      SUPPOTT TECH
      {%  endblock    %}
    </title>  

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="{% static 'lib/AdminLTE/plugins/jquery/jquery.min.js'  %}"></script>
  <!-- Bootstrap 4 -->
  <script src="{% static 'lib/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js'  %}"></script>
  <!-- AdminLTE App -->
  <script src="{% static 'lib/AdminLTE/js/adminlte.min.js'  %}"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'lib/AdminLTE/css/adminlte.min.css' %}">
  <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'lib/AdminLTE/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- jQuery -->
  <!-- Jquery Confirm -->
  <link rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
  <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
  <script src="{% static 'js/funciones2.js' %}"></script>

  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  
  <!-- Theme style -->
  {%  block styles %}
  {%  endblock  %} 
  {%  block scripts %}
  {%  endblock  %}  
</head>
<body class="hold-transition sidebar-mini layout-fixed" id="main">
  <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Sidebar -->
        {% include 'sidebar.html' %} 
        <!-- Content -->
        <div class="content-wrapper" id="hija">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>{{  request.user.username }}</small></h1>
                        </div>
                       
                    </div>
                </div>
            </div>
            <div class="content">
              <div class="container-fluid">
                  {% block content %}

                  {% endblock %}
              </div>
          </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
  <!-- ./wrapper -->
  
  <!-- REQUIRED SCRIPTS -->
  {% if not user.is_superuser %}
  <script>
    document.getElementById("main").style.marginLeft= "-230px";
    document.getElementById("hija").style.marginLeft= "230px";

  </script>
  
  {% else %}
  <script>
    function openNav() {        
      document.getElementById("mySidebar").style.width = "250px";
      document.getElementById("main").style.marginLeft = "0";
    }
    
    function closeNav() {
      document.getElementById("mySidebar").style.width = "0";
      document.getElementById("main").style.marginLeft= "-230px";
    }
  </script>
  {% endif %}
  
  
</body>
</html>

support_tech/templates/base2.html
{%  load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" href="{%  static 'img/logo1mejorado.png' %}">
  
    <title>
      {%  block title %}
      Zoopecas
      {%  endblock    %}
    </title>  

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="{% static 'lib/AdminLTE/plugins/jquery/jquery.min.js'  %}"></script>
  <!-- Bootstrap 4 -->
  <script src="{% static 'lib/AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js'  %}"></script>
  <!-- AdminLTE App -->
  <script src="{% static 'lib/AdminLTE/js/adminlte.min.js'  %}"></script>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <!-- Font Awesome Icons -->
  <link rel="stylesheet" href="{% static 'lib/AdminLTE/css/adminlte.min.css' %}">
  <script src="{% static 'fontawesomefree/js/all.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'lib/AdminLTE/plugins/fontawesome-free/css/all.min.css' %}">

  <script src="{% static 'js/funciones2.js' %}"></script>
  <link rel="stylesheet" href="{% static 'css/index.css' %}">
  <!-- Theme style -->
  {%  block styles %}
  {%  endblock  %} 
  {%  block scripts %}
  {%  endblock  %}  
</head>
<body class="hold-transition sidebar-mini layout-fixed" id="main">
  <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Sidebar -->
        {% if user.is_superuser %}
          {% include 'sidebar.html' %} 
        {% else %}
        {% endif %}       
        <!-- Content -->
        <div class="content-wrapper" id="hija">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>Veterinaria Zoopecas</small></h1>
                        </div>
                       
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
  <!-- ./wrapper -->

  <!-- REQUIRED SCRIPTS -->
    {% if not user.is_superuser %}
    <script>
      document.getElementById("main").style.marginLeft= "-230px";
      document.getElementById("hija").style.marginLeft= "230px";

    </script>
    
    {% else %}
    <script>
      function openNav() {        
        document.getElementById("mySidebar").style.width = "250px";
        document.getElementById("main").style.marginLeft = "0";
      }
      
      function closeNav() {
        document.getElementById("mySidebar").style.width = "0";
        document.getElementById("main").style.marginLeft= "-230px";
      }
    </script>
    {% endif %}
    

  
  
</body>
</html>

support_tech/templates/footer.html
{%  load static %}

<!-- Main Footer -->
<footer class="text-muted text-center text-small footer">
    <div class="row">
      <div class="col-lg-12  p-3">
        <p class="mb-1 fotterlist textColor">&copy; 2023 Support Tech</p>
        <ul class="list-inline fotterlist">
          <li class="list-inline-item "><a class="textColor" href="#">Terms</a></li>
          <li class="list-inline-item "><a class="textColor" href="#">Privacy</a></li>
          <li class="list-inline-item "><a class="textColor" href="#">Support</a></li>
        </ul>
      </div>
      
    </div>
  </footer>

support_tech/templates/header.html
{%  load static %}

 <!-- Navbar -->
  <nav class="main-header navbar navbar-expand-md headerColor">
    

    <div class="container ">
      {% if user.is_superuser %}
      <button  class="navbar-brand openbtn">        
        <img src="{%  static 'img/support_tech_logo.jpg' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3 " style="opacity: .8; background-color: rgb(255, 255, 255);" height="80px" onclick="openNav()">
      </button>
      {% else %}        
        <img src="{%  static 'img/support_tech_logo.jpg' %}" alt="zoopecas" class="brand-image img-circle elevation-3 " style="opacity: .8; background-color: rgb(255, 255, 255);" height="80px" >
      
      {% endif %}
        <a href="{% url 'inicio'  %}" class="nav-link textColor" style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; font-size: x-large; font-weight: bold;">ZOOPECAS</a>
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars" style="color:#fff; font-size:28px;"></i>
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse order-3" id="navbarCollapse">
        <!-- Left navbar links -->
        <div class="container-fluid">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a href="{% url 'inicio'  %}" class="nav-link textColor">Inicio</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'venta_list'  %}" class="nav-link textColor">Ventas</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'clientes'  %}" class="nav-link textColor">Clientes</a>
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">           
            {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="btn btn-secondary" href="{% url 'logout' %}" tabindex="-1" aria-disabled="true">logout</a>
                </li>
                
                {% else %}
                  <li class="nav-item">
                    <a class="btn btn-success" href="{% url 'login' %}" tabindex="-1" aria-disabled="true">Login</a>
                  </li>
                {% endif %}
          </ul>
        </div>
      </div>

    </div>
  </nav>
  <!-- /.navbar -->

support_tech/templates/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4 " id="mySidebar">
    
    <div class="sidebar" >  
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{% static 'img/support_tech_logo.jpg' %}" class="img-circle elevation-2" alt="User Image">
            </div>
            {% if user.is_authenticated %}
            <div class="info">
                <a href="#" class="d-block">{{ request.user.username }}</a>
            </div>
            {% endif %}
            <div class="info">
                <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">
                </a>    

            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-header">Mantenimientos</li>
                <li class="nav-item">
                    <a href="{% url 'categoria'  %}" class="nav-link">
                        <i class="nav-icon fas fa-cubes"></i>
                        <p>
                            Categorías
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'inventario'  %}" class="nav-link">
                        <i class="nav-icon fas fa-boxes"></i>
                        <p>
                            Productos
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-computer"></i>
                        <p>
                            Registro Equipos
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'proveedores'  %}" class="nav-link">
                        <i class="nav-icon fas fa-truck-loading"></i>
                        <p>
                            Proveedores
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'clientes'  %}" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Clientes
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'venta_create'  %}" class="nav-link">
                        <i class="nav-icon fas fa-shopping-cart"></i>
                        <p>
                            Ventas
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'cotizacion_create'  %}" class="nav-link">
                        <i class="nav-icon fas fa-shopping-cart"></i>
                        <p>
                            Cotización
                        </p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-chart-bar"></i>
                        <p>
                            Reporte de Ventas
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</aside>